version: '3'

volumes:
  production_postgres_data: {}  
  production_caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: hobbify_production_django
    depends_on:      
      - redis
    env_file:
      - ./.envs/.production/.django      
    command: /start
  
  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: hobbify_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: hobbify_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: hobbify_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: hobbify_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
