name: Continuous Integration and Delivery
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Django
      run: docker build -t hobbify_production_django -f ./compose/production/django/Dockerfile .

    - name: Build images
      run: |
          docker-compose -f local.yml build
